name: "Pre-commit (composite)"
description: "Setup Python, optionally Biome, cache pre-commit env, and run pre-commit"

inputs:
  python_version:
    description: "Python version to use"
    required: false
    default: "3.x"
  enable_cache:
    description: "Caching of pre-commit environments"
    required: false
    default: "true"
  setup_biome:
    description: "Setup Biome"
    required: false
    default: "false"
  setup_rust:
    description: "Setup Rust toolchain"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5

    - name: Setup Biome
      if: ${{ inputs.setup_biome == 'true' }}
      uses: biomejs/setup-biome@v2

    - name: Setup Rust
      if: ${{ inputs.setup_rust == 'true' }}
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        components: clippy, rustfmt

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python_version }}
        cache: pip

    - name: Install pre-commit
      shell: bash
      run: pip install pre-commit

    - name: Cache pre-commit
      if: ${{ inputs.enable_cache == 'true' }}
      uses: actions/cache@v4
      # NOTE: include runner.name so caches are unique per runner and get invalidated when runner changes.
      # Previously, runners would fail with file not found errors when trying to restore cache key
      # on a different runner.
      with:
        path: |
          ~/.cache/pre-commit
        key: ${{ runner.os }}-${{ runner.name }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.name }}-pre-commit-

    - name: Run pre-commit
      shell: bash
      run: pre-commit run --all-files
