name: Pre-commit
description: "Run pre-commit"

inputs:
  python_version:
    description: "Python version to use"
    required: false
    default: "3.x"
  enable_cache:
    description: "Enable caching of pre-commit environments"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: create pre-commit requirements file
      shell: bash
      run: echo "pre_commit" > pre-commit-requirements.txt

    - name: setup python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python_version }}
        cache: pip
        cache-dependency-path: pre-commit-requirements.txt

    - name: install pre-commit
      shell: bash
      run: pip install -r pre-commit-requirements.txt && rm pre-commit-requirements.txt

    - name: cache pre-commit
      if: ${{ inputs.enable_cache == 'true' }}
      uses: actions/cache@v5
      # NOTE: include runner.name so caches are unique per runner and get invalidated when runner changes.
      # Previously, runners would fail with file not found errors when trying to restore cache key
      # on a different runner.
      with:
        path: |
          ~/.cache/pre-commit
        key: ${{ runner.os }}-${{ runner.name }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.name }}-pre-commit-

    - name: run pre-commit
      shell: bash
      run: pre-commit run --all-files
