name: megalinter
description: run megalinter

inputs:
  github_token:
    description: github token for MegaLinter
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: megalinter
      uses: oxsecurity/megalinter@v9
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        VALIDATE_ALL_CODEBASE: true
