name: "MegaLinter (composite)"
description: "Run MegaLinter with artifact upload and optional fix application"

inputs:
  github_token:
    description: "GitHub token for MegaLinter"
    required: false
    default: "${{ github.token }}"
  validate_all_codebase:
    description: "Set MegaLinter VALIDATE_ALL_CODEBASE (true/false)"
    required: false
    default: ""
  apply_fixes:
    description: "Apply linter fixes (all/none)"
    required: false
    default: "all"
  apply_fixes_event:
    description: "Event that triggers application of fixes (pull_request, push, all)"
    required: false
    default: "all"
  apply_fixes_mode:
    description: "How to apply fixes (commit or pull_request)"
    required: false
    default: "commit"

outputs:
  has_updated_sources:
    description: "Whether MegaLinter updated any sources"
    value: ${{ steps.ml.outputs.has_updated_sources }}

runs:
  using: "composite"
  steps:
    - name: MegaLinter
      id: ml
      uses: oxsecurity/megalinter@v9
      env:
        VALIDATE_ALL_CODEBASE: ${{ inputs.validate_all_codebase }}
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Archive production artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v5
      with:
        name: MegaLinter reports
        path: |
          megalinter-reports
          mega-linter.log

    - name: Compute fix conditions
      id: should_apply_fixes
      if: steps.ml.outputs.has_updated_sources == 1
      shell: bash
      run: |
        SHOULD_SKIP="${{ contains(github.event.head_commit.message, 'skip fix') }}"
        EVENT_MATCH="${{ inputs.apply_fixes_event == 'all' || inputs.apply_fixes_event == github.event_name }}"
        IS_SAME_REPO="${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}"
        IS_PR_MODE="${{ inputs.apply_fixes_mode == 'pull_request' }}"
        IS_COMMIT_MODE="${{ inputs.apply_fixes_mode == 'commit' }}"
        IS_NOT_MAIN="${{ github.ref != 'refs/heads/main' }}"

        if [[ "$SHOULD_SKIP" == "true" ]]; then
          echo "apply_pr_fixes=false" >> "$GITHUB_OUTPUT"
          echo "apply_commit_fixes=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        if [[ "$EVENT_MATCH" == "true" && "$IS_SAME_REPO" == "true" ]]; then
          if [[ "$IS_PR_MODE" == "true" ]]; then
            echo "apply_pr_fixes=true" >> "$GITHUB_OUTPUT"
            echo "apply_commit_fixes=false" >> "$GITHUB_OUTPUT"
          elif [[ "$IS_COMMIT_MODE" == "true" && "$IS_NOT_MAIN" == "true" ]]; then
            echo "apply_pr_fixes=false" >> "$GITHUB_OUTPUT"
            echo "apply_commit_fixes=true" >> "$GITHUB_OUTPUT"
          else
            echo "apply_pr_fixes=false" >> "$GITHUB_OUTPUT"
            echo "apply_commit_fixes=false" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "apply_pr_fixes=false" >> "$GITHUB_OUTPUT"
          echo "apply_commit_fixes=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Create Pull Request with applied fixes
      id: cpr
      if: steps.should_apply_fixes.outputs.apply_pr_fixes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.github_token }}
        commit-message: "[MegaLinter] Apply linters automatic fixes"
        title: "[MegaLinter] Apply linters automatic fixes"
        labels: bot

    - name: Create PR output
      if: steps.should_apply_fixes.outputs.apply_pr_fixes == 'true'
      shell: bash
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

    - name: Prepare commit
      if: steps.should_apply_fixes.outputs.apply_commit_fixes == 'true'
      shell: bash
      run: sudo chown -Rc $UID .git/

    - name: Commit and push applied linter fixes
      if: steps.should_apply_fixes.outputs.apply_commit_fixes == 'true'
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
        commit_message: "lint(megalinter): apply linter fixes"
        commit_user_name: megalinter-bot
        commit_user_email: 129584137+megalinter-bot@users.noreply.github.com
